template_path: nlpsandbox.yaml
stack_name: nlpsandbox
parameters:
  Department: "CompOnc"
  Project: "nlpsandbox"
  OwnerEmail: "thomas.yu@sagebase.org"
  SSLCertificateIdArn: "arn:aws:acm:us-east-1:563295687221:certificate/07df27d5-a1fc-45f2-b70a-61ebda338153"
  #sandcastle vpc
  # VpcId: vpc-0e9b80dc470a797d5
  # Public Subnets
  PublicSubnets: "subnet-02f2acd15e5be53cd,subnet-031359c53fce9b312,subnet-0f19d4c62f9ab0f2c"
  # Private Subnets
  PrivateSubnets: "subnet-025c297e427e44daf,subnet-0bb4c519a4cbffcca,subnet-0b8a92e98f330a943"
stack_tags:
  name: nlpsandbox
