template_path: remote/vpc-mini.yaml
stack_name: nlpsandboxvpc
stack_tags:
  Department: "CompOnc"
  Project: "NLP Sandbox"
  OwnerEmail: "thomas.yu@sagebase.org"
parameters:
  VpcSubnetPrefix: "10.255.21"
  VpcName: nlpsandboxvpc
hooks:
  before_launch:
    - !cmd "wget https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/VPC/vpc-mini.yaml -N -P templates/remote"
