template_path: remote/vpc-mini.yaml
stack_name: nlpsandboxvpc
stack_tags:
  Department: "CompOnc"
  Project: "Nlp Sandbox"
  OwnerEmail: "thomas.yu@sagebase.org"
parameters:
  VpcSubnetPrefix: "10.255.20"
  VpcName: nlpsandboxvpc
hooks:
  before_launch:
    - !cmd "curl https://{{stack_group_config.admincentral_cf_bucket}}.s3.amazonaws.com/aws-infra/master/VPC/vpc-mini.yaml --create-dirs -o templates/remote/vpc-mini.yaml"
