name: aws-deploy

on:
  pull_request:
    branches: '*'
  push:
    branches: [main, develop]

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.2

  sceptre-deploy:
    name: Deploy CloudFormation templates using sceptre
    runs-on: ubuntu-latest
    needs: pre-commit
    if: github.ref == 'refs/heads/prod'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Assume AWS Role
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.CI_SERVICE_USER_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.CI_SERVICE_USER_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: arn:aws:iam::563295687221:role/NlpSandboxServiceAccount-ServiceRole-H1K0Q1UH2IX7
          role-duration-seconds: 1200
      - name: Deploy 'prod' templates
        uses: Sage-Bionetworks/sceptre-action@v1.1
        with:
          sceptre_version: 2.4.0
          sceptre_subcommand: launch --yes prod
