project_code: nlp-sandbox
# profile: {{ var.profile | default("default") }}
region: {{ var.region | default("us-east-1") }}
template_bucket_name: bootstrap-awss3cloudformationbucket-z6hnifi9i3p
template_key_prefix: {{ environment_variable.GITHUB_REF | default("testing") }}
admincentral_cf_bucket: "bootstrap-awss3cloudformationbucket-19qromfd235z9"
# Sender for notification hooks
# aws_account_name: Scicomp
# aws_account_email: aws.scicomp@sagebase.org
# # Provisioner defaults
# default_ami: "ami-082278746f893d99c"
# default_key_pair: "scicomp"
# default_vpc: "computevpc"
